{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envoy-proxy-bouncer.serviceAccountName" . }}
  labels:
    {{- include "envoy-proxy-bouncer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.serviceAccount.automount }}
automountServiceAccountToken: {{ . }}
{{- end }}
{{- end }}
