---
# Source: envoy-proxy-bouncer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-envoy-proxy-bouncer
  labels:
    helm.sh/chart: envoy-proxy-bouncer-0.0.1
    app.kubernetes.io/name: envoy-proxy-bouncer
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: envoy-proxy-bouncer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-envoy-proxy-bouncer
  labels:
    helm.sh/chart: envoy-proxy-bouncer-0.0.1
    app.kubernetes.io/name: envoy-proxy-bouncer
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: envoy-proxy-bouncer
    app.kubernetes.io/instance: release-name
---
# Source: envoy-proxy-bouncer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-envoy-proxy-bouncer
  labels:
    helm.sh/chart: envoy-proxy-bouncer-0.0.1
    app.kubernetes.io/name: envoy-proxy-bouncer
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-proxy-bouncer
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: envoy-proxy-bouncer-0.0.1
        app.kubernetes.io/name: envoy-proxy-bouncer
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-envoy-proxy-bouncer
      securityContext: {}
      containers:
        - name: envoy-proxy-bouncer
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "ghcr.io/kdwils/envoy-proxy-bouncer:0.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ENVOY_BOUNCER_BOUNCER_APIURL
              value: http://crowdsec-service:8080
            - name: ENVOY_BOUNCER_SERVER_PORT
              value: "8080"
            - name: ENVOY_BOUNCER_SERVER_LOGLEVEL
              value: info
            - name: ENVOY_BOUNCER_BOUNCER_APIKEY
              valueFrom:
                secretKeyRef:
                  name: crowdsec-api-key-secret
                  key: api-key
          livenessProbe:
            enabled: true
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            enabled: true
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
